### ISSUE TITLE
only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context

### ISSUE THREAD

**Issue by dogslife** [mikeheier/Redis-AS3#1]
Firstly, thanks for publishing this code. It may be the key to live updates in my flash app.
I've just started working with it and on occasion I get the following error
`only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context`

Is this something that I'm doing wrong?

**Comment by mikeheier** [comment]
Sorry for the late reply.  No problem, I hope this library helps you out.
That error is caused when you subscribe to a channel then run some other
command using the same connection.  Redis, for "pubsub" operations,
requires a dedicated connection for subscribing, so if you need to perform
any other action, such as publishing you need to create another connection
to perform those other commands.  The "subscribe" connection can subscribe
to multiple channels.The redis-util app is setup for pubsub operations if
you want to check it out.
