### ISSUE TITLE
Cannot connect to redis with flash app in the browser

### ISSUE THREAD

**Issue by dogslife** [mikeheier/Redis-AS3#3]
Have included this redis-AS3 client in my flash app and testing in the IDE it works blisteringly fast... just wow.. But When I launch my app in the browser it does not connect to redis at all, there are no errors just nothing. Is it me?

**Comment by mikeheier** [comment]
I have never tried to use this in a web app.  I'll try to throw something together real quick to test it out as soon as I can.

**Comment by mikeheier** [comment]
I added a web project to test it out.  Everything seems to work fine.  If you like, I can take a look at your code to see if anything is missing.

**Comment by mikeheier** [comment]
I apologize, my test was executed via the file protocol.  After testing on a local server, I received a sandbox violation error.

*** Security Sandbox Violation ***
Connection to 127.0.0.1:6379 halted - not permitted from http://127.0.0.1:8383/redis-web/RedisWeb.swf
Error: SWF from http://127.0.0.1:8383/redis-web/RedisWeb.swf may not connect to a socket in its own domain without a policy file.  See http://www.adobe.com/go/strict_policy_files to fix this problem.

Check out the "http://www.adobe.com/go/strict_policy_files" as stated above.
